defaults:
  - _self_
  - callbacks:
      - early_stopping
      - learning_rate_monitor
      - model_checkpoint
      - progress_bar
  - data: era5_cs64_7var_6h_24h
  - logger: tensorboard
  - model: cube_sphere_unet
  - trainer: default

experiment_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
checkpoint_path: null
load_weights_only: false
load_strict: true
seed: 0

batch_size: 32
learning_rate: 1e-3
num_workers: 8

hydra:
  verbose: true